name: Deploy to Netlify

on:
  pull_request:
    types: [closed]
    branches:
      - "release/**"

jobs:
  merge-to-production:
    if: github.event.pull_request.merged == true  # PR がマージされた場合のみ実行
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # full history is required for merge

      - name: Merge to production
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout production
          git merge --no-ff origin/${{ github.event.pull_request.base.ref }}
          git push origin production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}