name: Notify subscription renewal

on:
  schedule:
    - cron: '5 15 * * *'
  workflow_dispatch:

jobs:
  cron:
    name: Update exchange rate
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MAIL_ADDRESS_FOR_NOTIFICATION: ${{ secrets.MAIL_ADDRESS_FOR_NOTIFICATION }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Execute script
        run: bun script/notify-subscription-renewal.ts
