name: コールドスタートを防ぐための定期的なアクセス

on:
  schedule:
    - cron: '*/15 * * * *'  # 15分ごとに実行

jobs:
  curl_job:
    runs-on: ubuntu-latest
    steps:
      - name: Execute curl command
        run: curl -I https://substrack.jp/
