name: Update next update date

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  cron:
    name: Update exchange rate
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TZ: 'Asia/Tokyo'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Execute script
        run: bun script/update-next-update.ts
